image: node:14.6.0  # change to match your node version

cache:
  paths:
    - uberpage/node_modules/

before_script:
  - cd uberpage
  - npm install --global yarn
  - yarn install --immutable

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - CI=true yarn run lint

test:
  stage: test
  script:
    - CI=true yarn run test

build:
  stage: build
  script:
    - ../scripts/adjust_homepage.sh "https://stegschreck.gitlab.io"
    - cp -f src/data.gitlab.js src/data.js
    - CI=true yarn run build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - uberpage/build
  only:
    - master

pages:
  stage: deploy
  environment:
    name: production
    url: https://stegschreck.gitlab.io
  dependencies:
    - build
  script:
    - rm -rf ../public
    - mv build ../public
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch
