version: 0.2
env:
  variables:
    S3_BUCKET: "uberpage.schreck.berlin"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd uberpage/src
      - cp -f data.aws.js data.js
      - cd ..
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
     commands:
      - aws s3 cp build s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'uberpage/build*'
  discard-paths: yes
