export default {
  items: [
    {
      link: 'https://github.com/StegSchreck/AngularCV',
      description: 'Angular based online-CV',
      background_logo: 'AngularCV_white_transparent.svg',
    },
    {
      link: 'https://github.com/StegSchreck/RatS',
      text_color: '#FFFFFF',
      description: 'Python script for syncing movie ratings',
      background_logo: 'RatS_inverted.png',
      background_color: '#6D08A6',
    },
    {
      link: 'https://github.com/StegSchreck/uberpage',
      text_color: '#FFFFFF',
      description: 'React based overview page for several links',
      background_logo: 'UberPage_white.svg',
      background_color: '#4A86E8',
    },
    {
      link: 'https://github.com/StegSchreck/is24-price-per-area',
      text_color: '#FFFFFF',
      description: 'Chrome extension for displaying the price per m² on ImmobilienScout24 result lists',
      background_logo: 'is24-price-per-area_white.svg',
      background_logo_size: '25%',
      background_color: '#FF7300',
    },
    {
      link: 'https://github.com/StegSchreck/SpringerLinkEBookDownloader',
      text_color: '#002C5A',
      description: 'Download eBooks from a given list of Springer Link urls',
      background_logo: 'SpringerLinkEBookDownloader.svg',
      background_color: '#F1F1F1',
    },
    {
      link: 'https://github.com/StegSchreck/PP-Auxmoney-Parser',
      text_color: '#FFFFFF',
      description: 'Python script for parsing the received interests from Auxmoney to a CSV to be imported to Portfolio Performance',
      background_logo: 'PP-Auxmoney-Parser_white.svg',
      background_logo_size: '75%',
      background_color: '#275170',
    },
    {
      link: 'https://github.com/StegSchreck/PP-Trine-Parser',
      text_color: '#FFFFFF',
      description: 'Python script for parsing the received interests from Trine to a CSV to be imported to Portfolio Performance',
      background_logo: 'PP-Trine-Parser_white.svg',
      background_logo_size: '75%',
      background_color: '#54324F',
    },
    {
      link: 'https://github.com/StegSchreck/HistoricMarketPriceDownloader',
      text_color: '#FFFFFF',
      description: 'Python script for parsing all historic market prices of a stock to a CSV to be imported to Portfolio Performance',
      background_logo: 'HistoricMarketPriceDownloader_white.png',
      background_logo_size: '50%',
      background_color: '#009688',
    },
    {
      link: 'https://github.com/StegSchreck/AWSreCalendar',
      description: 'Python script for planning my stay at AWS re:Invent 2018',
      background_logo: 'AWSreCalendar.png',
      background_logo_size: 'contain',
      background_color: '#FF9900',
    },
    {
      link: 'https://github.com/StegSchreck/RecodingAviation',
      description: 'Angular app for hackathon reCoding Aviation 2017',
      background_logo: 'ReCodingAviation.png',
      background_logo_size: 'contain',
      background_color: '#E30613',
    },
    {
      link: 'https://github.com/WiSchLabs/Kicktipper',
      description: 'Calculating tips for football predictions games on Kicktipp',
      background_logo: 'Kicktipper.png',
      background_color: '#999999',
    },
    {
      link: 'https://github.com/WiSchLabs/ofm_helper',
      text_color: '#FFFFFF',
      description: 'Django based helper tool for onlinefussballmanager.de',
      background_logo: 'OFM_Helper_sw.png',
      background_color: '#239123',
    },
    {
      link: 'https://github.com/StegSchreck',
      text_color: '#FFFFFF',
      description: 'My profile page on GitHub',
      background_logo: 'GitHub_white.svg',
      background_color: '#000000',
    },
  ],
  settings: {
    default_link_target: '_blank',
    default_item: false,
  },
};
